FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/show_inventory.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_inventory_job.py /python/
COPY /python/Nexus9k_inventory.py /python/
COPY /scripts/inventory.sh /
COPY /Camelot/Show_Inventory/* /Camelot/Show_Inventory/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/inventory.sh"]