FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/learned_arp.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_learned_arp_job.py /python/
COPY /python/Nexus9k_learned_arp.py /python/
COPY /scripts/learned_arp.sh /
COPY /Camelot/Learned_ARP/* /Camelot/Learned_ARP/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/learned_arp.sh"]