FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/learned_vrf.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_learned_vrf_job.py /python/
COPY /python/Nexus9k_learned_vrf.py /python/
COPY /scripts/learned_vrf.sh /
COPY /Camelot/Learned_VRF/* /Camelot/Learned_VRF/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/learned_vrf.sh"]