FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/learned_interface.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_learned_interface_job.py /python/
COPY /python/Nexus9k_learned_interface.py /python/
COPY /scripts/learned_interface.sh /
COPY /Camelot/Learned_Interface/* /Camelot/Learned_Interface/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/learned_interface.sh"]