version: '3.8'
services:
  learned_acl:
    image: johncapobianco/merlin:learned_acl
    build: 
      context: ./
      dockerfile: ./docker/Learned_ACL/dockerfile
  learned_arp:
    image: johncapobianco/merlin:learned_arp
    build: 
      context: ./
      dockerfile: ./docker/Learned_ARP/dockerfile
  learned_bgp:
    image: johncapobianco/merlin:learned_bgp
    build: 
      context: ./
      dockerfile: ./docker/Learned_BGP/dockerfile            
  learned_interface:
    image: johncapobianco/merlin:learned_interface
    build: 
      context: ./
      dockerfile: ./docker/Learned_Interface/dockerfile
  learned_platform:
    image: johncapobianco/merlin:learned_platform
    build: 
      context: ./
      dockerfile: ./docker/Learned_Platform/dockerfile
  learned_routing:
    image: johncapobianco/merlin:learned_routing
    build: 
      context: ./
      dockerfile: ./docker/Learned_Routing/dockerfile
  learned_vlan:
    image: johncapobianco/merlin:learned_vlan
    build: 
      context: ./
      dockerfile: ./docker/Learned_VLAN/dockerfile
  learned_vrf:
    image: johncapobianco/merlin:learned_vrf
    build: 
      context: ./
      dockerfile: ./docker/Learned_VRF/dockerfile       
  access_lists:
    image: johncapobianco/merlin:access_lists
    build: 
      context: ./
      dockerfile: ./docker/Access_Lists/dockerfile
  bgp_process_vrf_all:
    image: johncapobianco/merlin:bgp_process_vrf_all
    build: 
      context: ./
      dockerfile: ./docker/BGP_Process_VRF_All/dockerfile            
  ip_int_brief:
    image: johncapobianco/merlin:xpresso_ip_int_brief
    build: 
      context: ./
      dockerfile: ./docker/IP_Int_Brief/dockerfile