version: '3.8'
services:
  learned_acl:
    image: johncapobianco/merlin:learned_acl
    build: 
      context: ./
      dockerfile: ./docker/Learned_ACL/dockerfile
  learned_routing:
    image: johncapobianco/merlin:learned_routing
    build: 
      context: ./
      dockerfile: ./docker/Learned_Routing/dockerfile      
  ip_int_brief:
    image: johncapobianco/merlin:ip_int_brief
    build: 
      context: ./
      dockerfile: ./docker/IP_Int_Brief/dockerfile
