FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/learned_acl.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_learned_acl_job.py /python/
COPY /python/Nexus9k_learned_acl.py /python/
COPY /scripts/learned_acl.sh /
COPY /Camelot/Learned_ACL/* /Camelot/Learned_ACL/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/learned_acl.sh"]