FROM johncapobianco/merlin:base_image

COPY /templates/cisco/api/psirt.j2 /templates/cisco/api/
COPY /api_credentials/cisco.yaml /api_credentials/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_psirt_job.py /python/
COPY /python/Nexus9k_psirt.py /python/
COPY /scripts/psirt.sh /
COPY /Camelot/PSIRT/* /Camelot/PSIRT/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/psirt.sh"]