FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/show_version.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_version_job.py /python/
COPY /python/Nexus9k_version.py /python/
COPY /scripts/version.sh /
COPY /Camelot/Show_Version/* /Camelot/Show_Version/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/version.sh"]