FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/show_ip_ospf.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_ip_ospf_job.py /python/
COPY /python/Nexus9k_ip_ospf.py /python/
COPY /scripts/ip_ospf.sh /
COPY /Camelot/Show_IP_OSPF/* /Camelot/Show_IP_OSPF/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/ip_ospf.sh"]