FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/show_bgp_process_vrf_all.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_bgp_process_vrf_all_job.py /python/
COPY /python/Nexus9k_bgp_process_vrf_all.py /python/
COPY /scripts/bgp_process_vrf_all.sh /
COPY /Camelot/Show_BGP_Process_VRF_All/* /Camelot/Show_BGP_Process_VRF_All/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/bgp_process_vrf_all.sh"]