FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/show_vlan.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_vlan_job.py /python/
COPY /python/Nexus9k_vlan.py /python/
COPY /scripts/vlan.sh /
COPY /Camelot/Show_VLAN/* /Camelot/Show_VLAN/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/vlan.sh"]