FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/learned_vlan.j2 /templates/cisco/nxos/
COPY /templates/cisco/nxos/elastic_standards.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_learned_vlan_job.py /python/
COPY /python/Nexus9k_learned_vlan.py /python/
COPY /scripts/learned_vlan.sh /
COPY /Camelot/Learned_VLAN/* /Camelot/Learned_VLAN/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/learned_vlan.sh"]