FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/learned_config.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_learned_config_job.py /python/
COPY /python/Nexus9k_learned_config.py /python/
COPY /scripts/learned_config.sh /
COPY /Camelot/Learned_Config/* /Camelot/Learned_Config/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/learned_config.sh"]