FROM johncapobianco/merlin:base_image

COPY /templates/cisco/nxos/show_ip_interface_brief.j2 /templates/cisco/nxos/
COPY /testbed/testbed_DevNet_Nexus9k_Sandbox.yaml /testbed/
COPY /python/general_functionalities.py /python/
COPY /python/Nexus9k_ip_int_brief_job.py /python/
COPY /python/Nexus9k_ip_int_brief.py /python/
COPY /scripts/ip_int_brief.sh /
COPY /Camelot/Show_IP_Interface_Brief/* /Camelot/Show_IP_Interface_Brief/
COPY /Camelot/styles.css /var/www/html/

CMD ["/bin/bash", "/ip_int_brief.sh"]